version: '3.9'

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - ./browsers.json:/etc/selenoid/browsers.json
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  tests:
    build: .
    network_mode: bridge
    depends_on:
      - selenoid
    volumes:
      - ./:/app
    working_dir: /app
    command: pytest --alluredir=/app/allure-results
