version: "3.9"

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid/config/:/etc/selenoid/:ro"
    restart: always

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenoid
    environment:
      - SELENOID_URL=http://selenoid:4444/wd/hub
    command: pytest
    volumes:
      - ./:/app
    working_dir: /app
